services:
    matm.typeahead:
        class: MatM\Bundle\TypeAheadBundle\Form\Type\TypeAheadType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: typeahead }

    matm.dataset_maker:
        class: MatM\Bundle\TypeAheadBundle\Services\TypeAheadManager