services:
    matm.typeahead_transformer:
        class: MatM\Bundle\TypeAheadBundle\Form\DataTransformer\TypeAheadType
        arguments: ["@doctrine.orm.entity_manager"]

    matm.typeahead_type:
        class: MatM\Bundle\TypeAheadBundle\Form\Type\TypeAheadTransformer
        arguments: ["matm.typeahead_transformer"]
        tags:
            - { name: form.type, alias: typeahead }

    matm.dataset_maker:
        class: MatM\Bundle\TypeAheadBundle\Services\TypeAheadDataBuilder
